name: Radon
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  radon:
    name: Radon
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Environment
        run: |
          chmod +x ./.github/workflows/setup.sh && ./.github/workflows/setup.sh
          pip install radon
      
      - name: Run Radon
        run: |
          output=$(radon cc hw2_debugging.py rand.py -a -nc)
          echo "::notice title=Radon::$output"