name: Run Testsuite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testsuite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4